### ISSUE TITLE
Please support to me !

### ISSUE THREAD

**Issue by phongtq2305** [eeftychiou/airplane-detection#1]
python3 detect.py --cascade classifier/cascade.xml --video samplevid/plane.mp4 --showHaarDetections
Traceback (most recent call last):
  File "detect.py", line 8, in <module>
    from common import clock, draw_str
  File "/Users/tranphong/projectpython/airplane-detection-master/common.py", line 73
    def draw_str(dst, (x, y), s):

**Comment by eeftychiou** [comment]
You need python 2.7
